name: SimBootstrap CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore SimBootstrap.CI.sln

    - name: Build Solution
      run: dotnet build SimBootstrap.CI.sln

    - name: Run Tests
      run: dotnet test SimBootstrap.CI.sln
